# Generated by Django 2.1.4 on 2018-12-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181224_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='option',
        ),
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='pollOptionAssociation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.PollOptionAssociation'),
        ),
    ]
